version: '3'

services:
  django:
    image: django
    environment:
      - CONFIG_PATH=common/configs/prod.cfg
    command: gunicorn --access-logfile - --workers 3 --max-requests 1000 --max-requests-jitter 50 --bind 0.0.0.0:8000 --env CONFIG_PATH=common/configs/prod.cfg myproject.wsgi:application --prometheus-exporter-port 9797
    ports:
      - "8000:8000"
    depends_on:
      - celery      
    networks:
      - django-network


  celery:
    image: django
    environment:
      - CONFIG_PATH=common/configs/prod.cfg
      - DJANGO_SETTINGS_MODULE=myproject.settings
    command: celery -A myproject worker -l info -Q myproject
    networks:
      - django-network


  consumer:
    image: django
    environment:
      - CONFIG_PATH=common/configs/prod.cfg
      - DJANGO_SETTINGS_MODULE=myproject.settings
    command: python consumer.py
    networks:
      - django-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - django
    networks:
      - django-network

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    depends_on:
      - prometheus
    networks:
      - django-network

networks:
  django-network:
    driver: bridge
