version: '3'

services:
  django:
    image: 556431762846.dkr.ecr.ap-south-1.amazonaws.com/django-project
    environment:
      - CONFIG_PATH=common/configs/prod.cfg
    command: gunicorn --access-logfile - --workers 3 --max-requests 1000 --max-requests-jitter 50 --bind 0.0.0.0:8000 --env CONFIG_PATH=common/configs/prod.cfg myproject.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - celery
      - consumer
    networks:
      - django-network


  celery:
    image: 556431762846.dkr.ecr.ap-south-1.amazonaws.com/django-project
    environment:
      - CONFIG_PATH=common/configs/prod.cfg
      - DJANGO_SETTINGS_MODULE=myproject.settings
    command: celery -A myproject worker -l info -Q myproject
    networks:
      - django-network


  consumer:
    image: 556431762846.dkr.ecr.ap-south-1.amazonaws.com/django-project
    environment:
      - CONFIG_PATH=common/configs/prod.cfg
      - DJANGO_SETTINGS_MODULE=myproject.settings
    command: python consumer.py
    networks:
      - django-network

networks:
  django-network:
    driver: bridge
