global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django:9797']  # Update this to the actual Django service name

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:9798']  # Update this to the actual consumer service name

  - job_name: 'celery'
    static_configs:
      - targets: ['celery:9798']  # Update this to the actual Celery service name
