name: Django Migration Workflow

on:
  push:
    branches:
      - main

jobs:
  migrate_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Pull migrations branch if exists
        run: |
          git fetch origin migrations:migrations || true

          git branch
          git status

          git config pull.rebase false
          git pull --no-edit origin migrations --allow-unrelated-histories
        
      - name: Run Django migrations
        run: |
          export CONFIG_PATH=common/configs/prod.cfg
          make migrations

      - name: Commit and push new migration files
        run: |
          grep -vE '^\*\*/migrations/\*\*' .gitignore > .gitignore_temp
          mv .gitignore_temp .gitignore

          git add .
          git commit -m "Run Django migrations"
          git push origin migrations